export type ERROR_CODES = INFRAESTRUCTURE_ERROR_CODES | BUSSINESS_ERROR_CODES | UNKNOW_ERROR_CODES;

export enum INFRAESTRUCTURE_ERROR_CODES {
  NETWORK_ERROR,
  TIMEOUT,
  API_ERROR,
}

export enum BUSSINESS_ERROR_CODES {
  AGE_REQUIRED,
}

export enum UNKNOW_ERROR_CODES {
  UNKNOW_ERROR,
}
